### ISSUE TITLE
Data sets for the exome validation pipeline

### ISSUE THREAD

**Issue by guillermo-carrasco** [ohofmann/bcbio_pub#1]
So these are the files downloaded for the exome validation pipeline and their source, please tell me if that's what you wanted. If so, I can add it to the paper markdown under a Validation --> Data section or so. 

| File name | Original file name | URL | Source |
| --- | --- | --- | --- |
| NA12878-NGv3-LAB1360-A_1.fastq.gz | NA12878-NGv3-LAB1360-A_1.fastq.gz | https://s3.amazonaws.com/bcbio_nextgen/NA12878-NGv3-LAB1360-A_1.fastq.gz | bcbio-nextgen amazon S3 bucket |
| NA12878-NGv3-LAB1360-A_2.fastq.gz | NA12878-NGv3-LAB1360-A_2.fastq.gz | https://s3.amazonaws.com/bcbio_nextgen/NA12878-NGv3-LAB1360-A_2.fastq.gz | bcbio-nextgen amazon S3 bucket |
| NGv3.bed.gz | NGv3.bed.gz | https://s3.amazonaws.com/bcbio_nextgen/NGv3.bed.gz | bcbio-nextgen amazon S3 bucket |
| GiaB_v2_19.vcf.gz | NISTIntegratedCalls_14datasets_131103_allcall_UGHapMerge_HetHomVarPASS_VQSRv2.19_2mindatasets_5minYesNoRatio_all_nouncert_excludesimplerep_excludesegdups_excludedecoy_excludeRepSeqSTRs_noCNVs.vcf.gz | ftp://ftp.ncbi.nlm.nih.gov/giab/ftp/release/NA12878_HG001/NISTv2.19/NISTIntegratedCalls_14datasets_131103_allcall_UGHapMerge_HetHomVarPASS_VQSRv2.19_2mindatasets_5minYesNoRatio_all_nouncert_excludesimplerep_excludesegdups_excludedecoy_excludeRepSeqSTRs_noCNVs.vcf.gz | NCBI - GiaB FTP server |
| GiaB_v2_19_regions.bed.gz | union13callableMQonlymerged_addcert_nouncert_excludesimplerep_excludesegdups_excludedecoy_excludeRepSeqSTRs_noCNVs_v2.19_2mindatasets_5minYesNoRatio.bed.gz | ftp://ftp.ncbi.nlm.nih.gov/giab/ftp/release/NA12878_HG001/NISTv2.19/union13callableMQonlymerged_addcert_nouncert_excludesimplerep_excludesegdups_excludedecoy_excludeRepSeqSTRs_noCNVs_v2.19_2mindatasets_5minYesNoRatio.bed.gz | NCBI - GiaB FTP server |

**Comment by ohofmann** [comment]
Guillermo, 

that's perfect. For the s3 bucket data we need to identify the original source -- the [README](https://github.com/ohofmann/bcbio_pub/blob/master/README.md) has some pointers to the Platinum Genomes and GiaB repositories. Just add it as `datasources.md` (or similar) to this repo and we can all add to it.

Oliver

**Comment by guillermo-carrasco** [comment]
Ok, thanks for the pointer!
